version: '3.8'

services:

  web:
    image: project_web
    container_name: web_container
    env_file:
      - ./.env.prod
    ports:
      - "8000:8000"
    depends_on:
      - alembic
    networks:
      - project_network

  db:
    image: postgis/postgis:16-3.4
    container_name: project_db
    restart: always
    env_file:
      - ./.env.db
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - project_network

  alembic:
    image: project_web
    env_file:
      - ./.env.prod
    command: [ "alembic", "upgrade", "head" ]
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
    networks:
      - project_network

volumes:
  postgres_data:

networks:
  project_network:
    driver: bridge

